name: Branch Protection Rules on Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent Direct Push
        run: |
          echo "Direct pushes to main are not allowed. Please use pull requests."
          exit 1
